### PR TITLE
Updating readme, fixing a missing enum variant

### PR DESCRIPTION
**Pull request by yaleman**
* There's a `4` response coming back when all files don't have the same priority, which was causing deserialisation to fail.
* The README example didn't work for me, had to import `Credential` from `qbit_rs::model`.

### CODE REVIEW

**Comment by George-Miao** [comment]
Please use nightly toolchain to format the code. There's a `rustfmt.toml` which uses nightly features.

**Comment by George-Miao** [comment]
The fmt result seems different on my machine. Did you use nightly toolchain to format the code?

**Comment by yaleman** [comment]
I have v1.73.0 stable installed

**Comment by George-Miao** [comment]
It's ok. I have formatted it.

**Pull request merged**
