### PR TITLE
add api torrent/export

### PR DESCRIPTION
**Pull request by shenjiangqiu**
torrent/export have been introduced since QBittorrent 4.5

### CODE REVIEW

**Comment by George-Miao** [comment]
I found the PR for this endpoint, but this seems like an undocumented api?

**Comment by shenjiangqiu** [comment]
Yes, it's undocumented. But it has been implemented in the official WebUI, and also the Python library.

**Comment by George-Miao** [comment]
I see, we should add this then.

**Review by George-Miao — APPROVED** [review]
LGTM

**Pull request merged**
